import SmallHeader from '@/component/header/page'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Age Calculator',
  description: 'Generated by Deepak',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <SmallHeader/>
        <p>Created by Deepak</p>
        </body>
    </html>
  )
}
